/// Từ vựng TOEIC hay gặp kèm PHIÊN ÂM (IPA giọng Mỹ - khớp giọng đọc en-US
/// của app), từ loại, câu ví dụ + dịch, và mẹo phát âm cho những từ hay bị
/// đọc sai (âm câm, trọng âm đổi theo từ loại, từ đồng âm dễ nhầm). Dùng cho
/// thẻ từ vựng xoay vòng ở màn chờ (`presentation/screens/boot/boot_screen.dart`).
///
/// Quy ước IPA: dấu ˈ đặt TRƯỚC âm tiết nhấn chính, ˌ trước âm tiết nhấn phụ,
/// dấu chấm tách âm tiết (giống từ điển Cambridge).
library;

class ToeicWord {
  final String word;
  final String ipa;

  /// n / v / adj / adv / phr / prep - xem [typeLabel].
  final String type;
  final String meaning;
  final String example;
  final String exampleVi;

  /// Mẹo phát âm/cách dùng - chỉ có ở những từ dễ sai.
  final String? tip;

  const ToeicWord(this.word, this.ipa, this.type, this.meaning, this.example, this.exampleVi, {this.tip});

  String get typeLabel => switch (type) {
        'n' => 'danh từ',
        'v' => 'động từ',
        'adj' => 'tính từ',
        'adv' => 'trạng từ',
        'prep' => 'giới từ',
        _ => 'cụm từ',
      };
}

class ToeicVocab {
  ToeicVocab._();

  static const List<ToeicWord> all = [
    // Văn phòng / hành chính
    ToeicWord('invoice', '/ˈɪn.vɔɪs/', 'n', 'hoá đơn',
        'Please send the invoice to the accounting department.', 'Vui lòng gửi hoá đơn cho phòng kế toán.'),
    ToeicWord('deadline', '/ˈded.laɪn/', 'n', 'hạn chót',
        'The deadline for the report is Friday.', 'Hạn chót nộp báo cáo là thứ Sáu.'),
    ToeicWord('colleague', '/ˈkɑː.liːɡ/', 'n', 'đồng nghiệp',
        'I had lunch with a colleague from marketing.', 'Tôi ăn trưa với một đồng nghiệp bên marketing.', tip: 'Nhấn âm đầu: KAH-leeg, "ue" cuối câm.'),
    ToeicWord('attachment', '/əˈtætʃ.mənt/', 'n', 'tệp đính kèm',
        'Please open the attachment for details.', 'Vui lòng mở tệp đính kèm để xem chi tiết.'),
    ToeicWord('agenda', '/əˈdʒen.də/', 'n', 'chương trình cuộc họp',
        'The first item on the agenda is the budget.', 'Mục đầu tiên trong chương trình họp là ngân sách.'),
    ToeicWord('memo', '/ˈmem.oʊ/', 'n', 'thông báo nội bộ',
        'The manager sent a memo about the new dress code.', 'Quản lý gửi thông báo nội bộ về quy định trang phục mới.'),
    ToeicWord('stationery', '/ˈsteɪ.ʃə.ner.i/', 'n', 'văn phòng phẩm',
        'We need to order more stationery this month.', 'Tháng này ta cần đặt thêm văn phòng phẩm.', tip: 'Đọc giống hệt "stationary" (đứng yên) - phân biệt bằng ngữ cảnh.'),
    ToeicWord('photocopier', '/ˈfoʊ.toʊˌkɑː.pi.ɚ/', 'n', 'máy photocopy',
        'The photocopier on the second floor is out of order.', 'Máy photocopy ở tầng 2 bị hỏng.'),
    ToeicWord('receptionist', '/rɪˈsep.ʃən.ɪst/', 'n', 'lễ tân',
        'Please check in with the receptionist.', 'Vui lòng đăng ký với lễ tân.'),
    ToeicWord('workplace', '/ˈwɝːk.pleɪs/', 'n', 'nơi làm việc',
        'Safety in the workplace is our top priority.', 'An toàn nơi làm việc là ưu tiên hàng đầu.'),
    ToeicWord('overtime', '/ˈoʊ.vɚ.taɪm/', 'n', 'làm thêm giờ',
        'Staff who work overtime will be paid extra.', 'Nhân viên làm thêm giờ sẽ được trả thêm.'),
    ToeicWord('shift', '/ʃɪft/', 'n', 'ca làm việc',
        'She works the night shift at the hospital.', 'Cô ấy làm ca đêm ở bệnh viện.'),
    ToeicWord('extension', '/ɪkˈsten.ʃən/', 'n', 'số máy lẻ; sự gia hạn',
        'Please call me at extension 205.', 'Vui lòng gọi tôi ở số máy lẻ 205.'),
    ToeicWord('voicemail', '/ˈvɔɪs.meɪl/', 'n', 'hộp thư thoại',
        'I left a voicemail for Mr. Tanaka.', 'Tôi đã để lại tin nhắn thoại cho ông Tanaka.'),
    ToeicWord('printout', '/ˈprɪnt.aʊt/', 'n', 'bản in',
        'Bring a printout of the schedule to the meeting.', 'Mang bản in lịch trình tới cuộc họp.'),
    ToeicWord('cubicle', '/ˈkjuː.bɪ.kəl/', 'n', 'ô làm việc có vách ngăn',
        'My cubicle is next to the window.', 'Ô làm việc của tôi ở cạnh cửa sổ.'),
    ToeicWord('filing cabinet', '/ˈfaɪ.lɪŋ ˌkæb.ɪ.nət/', 'n', 'tủ đựng hồ sơ',
        'The contracts are in the filing cabinet.', 'Các hợp đồng nằm trong tủ hồ sơ.'),
    ToeicWord('supplies', '/səˈplaɪz/', 'n', 'đồ dùng, vật tư',
        'Office supplies are kept in the storage room.', 'Đồ dùng văn phòng được cất trong phòng kho.'),
    ToeicWord('correspondence', '/ˌkɔːr.əˈspɑːn.dəns/', 'n', 'thư từ giao dịch',
        'All correspondence should be sent to our new address.', 'Mọi thư từ nên gửi tới địa chỉ mới của chúng tôi.'),
    ToeicWord('reminder', '/rɪˈmaɪn.dɚ/', 'n', 'lời nhắc',
        'This is a reminder that the office closes early today.', 'Xin nhắc rằng hôm nay văn phòng đóng cửa sớm.'),
    // Họp hành / dự án
    ToeicWord('supervisor', '/ˈsuː.pɚ.vaɪ.zɚ/', 'n', 'người giám sát',
        'Report any problems to your supervisor.', 'Hãy báo mọi vấn đề cho người giám sát của bạn.'),
    ToeicWord('negotiate', '/nəˈɡoʊ.ʃi.eɪt/', 'v', 'đàm phán',
        'We are negotiating a new contract with the supplier.', 'Chúng tôi đang đàm phán hợp đồng mới với nhà cung cấp.'),
    ToeicWord('feedback', '/ˈfiːd.bæk/', 'n', 'ý kiến phản hồi',
        'Thank you for your feedback on our service.', 'Cảm ơn góp ý của bạn về dịch vụ của chúng tôi.'),
    ToeicWord('productivity', '/ˌproʊ.dʌkˈtɪv.ə.ti/', 'n', 'năng suất',
        'The new software has improved productivity.', 'Phần mềm mới đã cải thiện năng suất.'),
    ToeicWord('headquarters', '/ˈhedˌkwɔːr.tɚz/', 'n', 'trụ sở chính',
        'Our headquarters is located in Seoul.', 'Trụ sở chính của chúng tôi đặt tại Seoul.', tip: 'Luôn có "s" ở cuối nhưng vẫn có thể đi với động từ số ít.'),
    ToeicWord('conference', '/ˈkɑːn.fɚ.əns/', 'n', 'hội nghị',
        'She is attending a conference in Tokyo.', 'Cô ấy đang dự hội nghị ở Tokyo.'),
    ToeicWord('presentation', '/ˌprez.ənˈteɪ.ʃən/', 'n', 'bài thuyết trình',
        'His presentation on sales was very clear.', 'Bài thuyết trình về doanh số của anh ấy rất rõ ràng.'),
    ToeicWord('proposal', '/prəˈpoʊ.zəl/', 'n', 'bản đề xuất',
        'The board approved the proposal.', 'Hội đồng đã duyệt bản đề xuất.'),
    ToeicWord('postpone', '/poʊstˈpoʊn/', 'v', 'hoãn lại',
        'The meeting was postponed until Monday.', 'Cuộc họp bị hoãn tới thứ Hai.', tip: 'Chữ "t" gần như không nghe thấy: pohs-POHN.'),
    ToeicWord('reschedule', '/ˌriːˈskedʒ.uːl/', 'v', 'sắp xếp lại lịch',
        'Can we reschedule the interview for Thursday?', 'Ta dời lịch phỏng vấn sang thứ Năm được không?', tip: 'Giọng Mỹ đọc "ree-SKEJ-ool", giọng Anh đọc "ree-SHED-yool".'),
    ToeicWord('participant', '/pɑːrˈtɪs.ə.pənt/', 'n', 'người tham gia',
        'Each participant will receive a certificate.', 'Mỗi người tham gia sẽ nhận một chứng nhận.'),
    ToeicWord('brainstorm', '/ˈbreɪn.stɔːrm/', 'v', 'cùng nghĩ ý tưởng',
        'Let\'s brainstorm ideas for the new campaign.', 'Hãy cùng nghĩ ý tưởng cho chiến dịch mới.'),
    ToeicWord('minutes', '/ˈmɪn.ɪts/', 'n', 'biên bản cuộc họp',
        'Linda will take the minutes at today\'s meeting.', 'Linda sẽ ghi biên bản cuộc họp hôm nay.'),
    ToeicWord('milestone', '/ˈmaɪl.stoʊn/', 'n', 'cột mốc quan trọng',
        'Reaching one million users was a major milestone.', 'Đạt 1 triệu người dùng là một cột mốc lớn.'),
    ToeicWord('collaborate', '/kəˈlæb.ə.reɪt/', 'v', 'hợp tác, cộng tác',
        'Our team collaborated with designers in Paris.', 'Nhóm chúng tôi đã cộng tác với các nhà thiết kế ở Paris.'),
    ToeicWord('consensus', '/kənˈsen.səs/', 'n', 'sự đồng thuận',
        'The team finally reached a consensus.', 'Cuối cùng cả nhóm đã đạt được đồng thuận.'),
    ToeicWord('objective', '/əbˈdʒek.tɪv/', 'n', 'mục tiêu',
        'Our main objective is to reduce costs.', 'Mục tiêu chính của chúng ta là giảm chi phí.'),
    ToeicWord('progress report', '/ˈprɑː.ɡres rɪˌpɔːrt/', 'n', 'báo cáo tiến độ',
        'Please submit a progress report every Friday.', 'Vui lòng nộp báo cáo tiến độ mỗi thứ Sáu.'),
    // Nhân sự / tuyển dụng
    ToeicWord('applicant', '/ˈæp.lə.kənt/', 'n', 'người ứng tuyển',
        'All applicants must have a driver\'s license.', 'Mọi người ứng tuyển phải có bằng lái xe.'),
    ToeicWord('résumé', '/ˈrez.ə.meɪ/', 'n', 'sơ yếu lý lịch',
        'Please attach your résumé to the email.', 'Vui lòng đính kèm sơ yếu lý lịch vào email.', tip: 'Danh từ đọc REZ-uh-may; động từ "resume" (tiếp tục) đọc ri-ZOOM.'),
    ToeicWord('candidate', '/ˈkæn.dɪ.dət/', 'n', 'ứng viên',
        'We interviewed three candidates for the position.', 'Chúng tôi đã phỏng vấn 3 ứng viên cho vị trí này.'),
    ToeicWord('interview', '/ˈɪn.tɚ.vjuː/', 'n', 'buổi phỏng vấn',
        'Your interview is scheduled for 10 A.M.', 'Buổi phỏng vấn của bạn được xếp lúc 10 giờ sáng.'),
    ToeicWord('qualification', '/ˌkwɑː.lə.fəˈkeɪ.ʃən/', 'n', 'bằng cấp, trình độ',
        'She has the right qualifications for the job.', 'Cô ấy có trình độ phù hợp với công việc.'),
    ToeicWord('promotion', '/prəˈmoʊ.ʃən/', 'n', 'sự thăng chức; khuyến mãi',
        'Mark received a promotion to sales manager.', 'Mark được thăng chức lên quản lý bán hàng.'),
    ToeicWord('salary', '/ˈsæl.ɚ.i/', 'n', 'lương',
        'The salary depends on experience.', 'Mức lương tuỳ theo kinh nghiệm.'),
    ToeicWord('benefits', '/ˈben.ə.fɪts/', 'n', 'phúc lợi',
        'The job offers excellent benefits, including health insurance.', 'Công việc có phúc lợi tốt, gồm cả bảo hiểm y tế.'),
    ToeicWord('vacancy', '/ˈveɪ.kən.si/', 'n', 'vị trí trống; phòng trống',
        'We have a vacancy in the finance department.', 'Phòng tài chính đang có một vị trí trống.'),
    ToeicWord('probation', '/proʊˈbeɪ.ʃən/', 'n', 'thời gian thử việc',
        'New employees have a three-month probation period.', 'Nhân viên mới có 3 tháng thử việc.'),
    ToeicWord('resignation', '/ˌrez.ɪɡˈneɪ.ʃən/', 'n', 'sự từ chức, đơn nghỉ việc',
        'He handed in his resignation yesterday.', 'Hôm qua anh ấy đã nộp đơn nghỉ việc.', tip: 'Chữ "g" ở đây ĐƯỢC đọc (rez-ig-NAY-shun), khác "resign" có "g" câm.'),
    ToeicWord('orientation', '/ˌɔːr.i.enˈteɪ.ʃən/', 'n', 'buổi định hướng nhân viên mới',
        'Orientation for new staff begins at 9 A.M.', 'Buổi định hướng cho nhân viên mới bắt đầu lúc 9 giờ.'),
    ToeicWord('job description', '/ˈdʒɑːb dɪˌskrɪp.ʃən/', 'n', 'bản mô tả công việc',
        'Please read the job description carefully.', 'Vui lòng đọc kỹ bản mô tả công việc.'),
    ToeicWord('performance review', '/pɚˈfɔːr.məns rɪˌvjuː/', 'n', 'đánh giá hiệu quả công việc',
        'Performance reviews are held twice a year.', 'Đánh giá hiệu quả công việc diễn ra 2 lần mỗi năm.'),
    ToeicWord('retire', '/rɪˈtaɪɚ/', 'v', 'nghỉ hưu',
        'Mr. Evans will retire at the end of the year.', 'Ông Evans sẽ nghỉ hưu vào cuối năm.'),
    ToeicWord('hire', '/haɪɚ/', 'v', 'thuê, tuyển',
        'We plan to hire ten new engineers.', 'Chúng tôi dự định tuyển 10 kỹ sư mới.'),
    ToeicWord('workforce', '/ˈwɝːk.fɔːrs/', 'n', 'lực lượng lao động',
        'Half of our workforce works from home.', 'Một nửa nhân lực của chúng tôi làm việc tại nhà.'),
    // Tài chính / kế toán
    ToeicWord('reimbursement', '/ˌriː.ɪmˈbɝːs.mənt/', 'n', 'khoản hoàn trả chi phí',
        'Submit your receipts for travel reimbursement.', 'Nộp hoá đơn để được hoàn tiền công tác phí.'),
    ToeicWord('budget', '/ˈbʌdʒ.ɪt/', 'n', 'ngân sách',
        'The project is within budget.', 'Dự án vẫn nằm trong ngân sách.'),
    ToeicWord('revenue', '/ˈrev.ə.nuː/', 'n', 'doanh thu',
        'Revenue increased by 10 percent last year.', 'Doanh thu tăng 10% năm ngoái.'),
    ToeicWord('expense', '/ɪkˈspens/', 'n', 'chi phí',
        'Hotel expenses will be covered by the company.', 'Chi phí khách sạn sẽ do công ty chi trả.'),
    ToeicWord('profit', '/ˈprɑː.fɪt/', 'n', 'lợi nhuận',
        'The company made a large profit this quarter.', 'Công ty có lợi nhuận lớn trong quý này.'),
    ToeicWord('discount', '/ˈdɪs.kaʊnt/', 'n', 'sự giảm giá',
        'Members get a 10 percent discount.', 'Hội viên được giảm giá 10%.'),
    ToeicWord('receipt', '/rɪˈsiːt/', 'n', 'biên lai',
        'Keep your receipt in case you need a refund.', 'Hãy giữ biên lai phòng khi cần hoàn tiền.', tip: 'Chữ "p" câm: ri-SEET.'),
    ToeicWord('installment', '/ɪnˈstɑːl.mənt/', 'n', 'khoản trả góp',
        'You can pay in three monthly installments.', 'Bạn có thể trả góp làm 3 lần hằng tháng.'),
    ToeicWord('surplus', '/ˈsɝː.pləs/', 'n', 'thặng dư',
        'The city had a budget surplus this year.', 'Năm nay thành phố có thặng dư ngân sách.'),
    ToeicWord('deficit', '/ˈdef.ə.sɪt/', 'n', 'thâm hụt',
        'The company is trying to reduce its deficit.', 'Công ty đang cố giảm thâm hụt.'),
    ToeicWord('audit', '/ˈɑː.dɪt/', 'n', 'cuộc kiểm toán',
        'The annual audit will take place in March.', 'Cuộc kiểm toán thường niên diễn ra vào tháng Ba.'),
    ToeicWord('fiscal', '/ˈfɪs.kəl/', 'adj', 'thuộc tài khoá',
        'The fiscal year ends on June 30.', 'Năm tài khoá kết thúc ngày 30 tháng 6.'),
    ToeicWord('payroll', '/ˈpeɪ.roʊl/', 'n', 'bảng lương',
        'Payroll is processed on the last day of the month.', 'Bảng lương được xử lý vào ngày cuối tháng.'),
    ToeicWord('quarterly', '/ˈkwɔːr.tɚ.li/', 'adj', 'hằng quý',
        'The quarterly report is due next week.', 'Báo cáo quý đến hạn vào tuần sau.'),
    ToeicWord('accounting', '/əˈkaʊn.tɪŋ/', 'n', 'kế toán',
        'Please send your invoices to accounting.', 'Vui lòng gửi hoá đơn cho phòng kế toán.'),
    ToeicWord('balance', '/ˈbæl.əns/', 'n', 'số dư',
        'Please pay the remaining balance by Friday.', 'Vui lòng thanh toán số tiền còn lại trước thứ Sáu.'),
    ToeicWord('overdue', '/ˌoʊ.vɚˈduː/', 'adj', 'quá hạn',
        'Your payment is two weeks overdue.', 'Khoản thanh toán của bạn đã quá hạn 2 tuần.'),
    ToeicWord('forecast', '/ˈfɔːr.kæst/', 'n', 'dự báo',
        'The sales forecast for next year looks positive.', 'Dự báo doanh số năm sau khả quan.'),
    // Kho vận / sản xuất
    ToeicWord('warehouse', '/ˈwer.haʊs/', 'n', 'nhà kho',
        'The goods are stored in our warehouse.', 'Hàng hoá được lưu trong kho của chúng tôi.'),
    ToeicWord('shipment', '/ˈʃɪp.mənt/', 'n', 'lô hàng',
        'The shipment will arrive on Tuesday.', 'Lô hàng sẽ tới vào thứ Ba.'),
    ToeicWord('inventory', '/ˈɪn.vən.tɔːr.i/', 'n', 'hàng tồn kho; việc kiểm kê',
        'We check our inventory every month.', 'Chúng tôi kiểm kê hàng tồn mỗi tháng.', tip: 'Nhấn âm đầu: IN-vən-tor-ee.'),
    ToeicWord('vendor', '/ˈven.dɚ/', 'n', 'nhà cung cấp, người bán',
        'We buy paper from a local vendor.', 'Chúng tôi mua giấy từ một nhà cung cấp địa phương.'),
    ToeicWord('supplier', '/səˈplaɪ.ɚ/', 'n', 'nhà cung ứng',
        'Our supplier raised its prices.', 'Nhà cung ứng của chúng tôi đã tăng giá.'),
    ToeicWord('delivery', '/dɪˈlɪv.ɚ.i/', 'n', 'việc giao hàng',
        'Delivery is free for orders over \$50.', 'Miễn phí giao hàng cho đơn trên 50 đô.'),
    ToeicWord('logistics', '/loʊˈdʒɪs.tɪks/', 'n', 'hậu cần',
        'She manages logistics for the event.', 'Cô ấy quản lý hậu cần cho sự kiện.'),
    ToeicWord('manufacture', '/ˌmæn.jəˈfæk.tʃɚ/', 'v', 'sản xuất',
        'The company manufactures car parts.', 'Công ty sản xuất linh kiện ô tô.'),
    ToeicWord('defective', '/dɪˈfek.tɪv/', 'adj', 'bị lỗi',
        'Defective items can be returned within 30 days.', 'Hàng lỗi có thể trả lại trong 30 ngày.'),
    ToeicWord('quality control', '/ˈkwɑː.lə.ti kənˌtroʊl/', 'n', 'kiểm soát chất lượng',
        'Every product goes through quality control.', 'Mọi sản phẩm đều qua khâu kiểm soát chất lượng.'),
    ToeicWord('packaging', '/ˈpæk.ɪ.dʒɪŋ/', 'n', 'bao bì',
        'The new packaging is made from recycled paper.', 'Bao bì mới làm từ giấy tái chế.'),
    ToeicWord('freight', '/freɪt/', 'n', 'hàng hoá vận chuyển',
        'The freight will be shipped by sea.', 'Hàng sẽ được vận chuyển bằng đường biển.', tip: '"gh" câm, đọc giống "FRATE".'),
    ToeicWord('assembly line', '/əˈsem.bli ˌlaɪn/', 'n', 'dây chuyền lắp ráp',
        'The assembly line produces 500 cars a day.', 'Dây chuyền lắp ráp sản xuất 500 xe mỗi ngày.'),
    ToeicWord('distributor', '/dɪˈstrɪb.jə.tɚ/', 'n', 'nhà phân phối',
        'We are looking for a distributor in Vietnam.', 'Chúng tôi đang tìm nhà phân phối tại Việt Nam.'),
    ToeicWord('in bulk', '/ɪn ˈbʌlk/', 'phr', 'với số lượng lớn',
        'Buying in bulk is cheaper.', 'Mua số lượng lớn thì rẻ hơn.'),
    ToeicWord('tracking number', '/ˈtræk.ɪŋ ˌnʌm.bɚ/', 'n', 'mã vận đơn',
        'Use the tracking number to check your order.', 'Dùng mã vận đơn để kiểm tra đơn hàng.'),
    // Du lịch / khách sạn
    ToeicWord('itinerary', '/aɪˈtɪn.ə.rer.i/', 'n', 'lịch trình',
        'Your travel itinerary is attached.', 'Lịch trình chuyến đi của bạn được đính kèm.', tip: 'Nhấn âm thứ hai: eye-TIN-ə-rer-ee.'),
    ToeicWord('reservation', '/ˌrez.ɚˈveɪ.ʃən/', 'n', 'việc đặt chỗ',
        'I\'d like to make a reservation for two.', 'Tôi muốn đặt chỗ cho 2 người.'),
    ToeicWord('boarding pass', '/ˈbɔːr.dɪŋ ˌpæs/', 'n', 'thẻ lên máy bay',
        'Please show your boarding pass at the gate.', 'Vui lòng xuất trình thẻ lên máy bay tại cổng.'),
    ToeicWord('luggage', '/ˈlʌɡ.ɪdʒ/', 'n', 'hành lý',
        'Each passenger may bring one piece of luggage.', 'Mỗi hành khách được mang một kiện hành lý.', tip: 'Danh từ KHÔNG đếm được: nói "a piece of luggage", không nói "a luggage".'),
    ToeicWord('departure', '/dɪˈpɑːr.tʃɚ/', 'n', 'sự khởi hành',
        'The departure time has changed to 3 P.M.', 'Giờ khởi hành đổi thành 3 giờ chiều.'),
    ToeicWord('customs', '/ˈkʌs.təmz/', 'n', 'hải quan',
        'It took an hour to go through customs.', 'Mất một tiếng để qua hải quan.'),
    ToeicWord('accommodation', '/əˌkɑː.məˈdeɪ.ʃən/', 'n', 'chỗ ở',
        'The price includes flights and accommodation.', 'Giá đã gồm vé máy bay và chỗ ở.', tip: 'Viết với 2 chữ "c" và 2 chữ "m".'),
    ToeicWord('receptacle', '/rɪˈsep.tə.kəl/', 'n', 'thùng chứa (rác...)',
        'Please put your trash in the receptacle.', 'Vui lòng bỏ rác vào thùng.'),
    ToeicWord('checkout', '/ˈtʃek.aʊt/', 'n', 'thủ tục trả phòng',
        'Checkout time is 11 A.M.', 'Giờ trả phòng là 11 giờ sáng.'),
    ToeicWord('concierge', '/ˌkɑːn.siˈerʒ/', 'n', 'nhân viên hỗ trợ khách (khách sạn)',
        'The concierge can book a taxi for you.', 'Nhân viên hỗ trợ có thể đặt taxi giúp bạn.', tip: 'Từ gốc Pháp: kahn-see-AIRZH.'),
    ToeicWord('round-trip', '/ˌraʊndˈtrɪp/', 'adj', 'khứ hồi',
        'A round-trip ticket costs \$300.', 'Vé khứ hồi giá 300 đô.'),
    ToeicWord('layover', '/ˈleɪˌoʊ.vɚ/', 'n', 'chặng dừng quá cảnh',
        'We have a two-hour layover in Singapore.', 'Chúng tôi quá cảnh 2 tiếng ở Singapore.'),
    ToeicWord('aisle seat', '/ˈaɪl ˌsiːt/', 'n', 'ghế cạnh lối đi',
        'I\'d prefer an aisle seat, please.', 'Tôi muốn ghế cạnh lối đi.', tip: '"s" trong "aisle" câm: đọc giống "I\'ll".'),
    ToeicWord('destination', '/ˌdes.təˈneɪ.ʃən/', 'n', 'điểm đến',
        'Bali is a popular destination.', 'Bali là điểm đến được ưa chuộng.'),
    ToeicWord('brochure', '/broʊˈʃʊr/', 'n', 'tờ gấp giới thiệu',
        'Take a brochure for more information.', 'Hãy lấy một tờ gấp để biết thêm thông tin.', tip: '"ch" đọc như "sh": broh-SHOOR.'),
    ToeicWord('suite', '/swiːt/', 'n', 'phòng hạng sang',
        'They booked a suite on the top floor.', 'Họ đặt một phòng hạng sang ở tầng thượng.', tip: 'Đọc giống "sweet", khác "suit" /suːt/ (bộ vest).'),
    // Marketing / bán hàng
    ToeicWord('subscription', '/səbˈskrɪp.ʃən/', 'n', 'gói đăng ký dịch vụ',
        'Your subscription will renew automatically.', 'Gói đăng ký của bạn sẽ tự gia hạn.'),
    ToeicWord('customer', '/ˈkʌs.tə.mɚ/', 'n', 'khách hàng',
        'Customer satisfaction is our priority.', 'Sự hài lòng của khách hàng là ưu tiên của chúng tôi.'),
    ToeicWord('advertisement', '/ˌæd.vɚˈtaɪz.mənt/', 'n', 'quảng cáo',
        'We placed an advertisement in the newspaper.', 'Chúng tôi đăng quảng cáo trên báo.', tip: 'Giọng Mỹ nhấn "TIZE" (ad-vər-TIZE-mənt), giọng Anh nhấn "VER" (əd-VER-tis-mənt).'),
    ToeicWord('brand', '/brænd/', 'n', 'thương hiệu',
        'The brand is popular with young people.', 'Thương hiệu này được giới trẻ ưa chuộng.'),
    ToeicWord('giveaway', '/ˈɡɪv.ə.weɪ/', 'n', 'quà tặng khuyến mãi',
        'The first 50 customers will get a free giveaway.', '50 khách đầu tiên sẽ nhận quà tặng.'),
    ToeicWord('retail', '/ˈriː.teɪl/', 'n', 'bán lẻ',
        'She has ten years of experience in retail.', 'Cô ấy có 10 năm kinh nghiệm bán lẻ.'),
    ToeicWord('wholesale', '/ˈhoʊl.seɪl/', 'n', 'bán sỉ',
        'We sell our products at wholesale prices.', 'Chúng tôi bán sản phẩm theo giá sỉ.', tip: '"w" câm: đọc "HOLE-sale".'),
    ToeicWord('client', '/ˈklaɪ.ənt/', 'n', 'khách hàng (doanh nghiệp)',
        'I\'m meeting a client at 2 P.M.', 'Tôi gặp một khách hàng lúc 2 giờ chiều.'),
    ToeicWord('coupon', '/ˈkuː.pɑːn/', 'n', 'phiếu giảm giá',
        'Use this coupon on your next visit.', 'Dùng phiếu giảm giá này cho lần mua sau.'),
    ToeicWord('warranty', '/ˈwɔːr.ən.ti/', 'n', 'sự bảo hành',
        'The laptop comes with a two-year warranty.', 'Laptop được bảo hành 2 năm.'),
    ToeicWord('refund', '/ˈriː.fʌnd/', 'n', 'khoản hoàn tiền',
        'You can get a full refund within 14 days.', 'Bạn được hoàn tiền toàn bộ trong 14 ngày.', tip: 'Danh từ nhấn âm 1 (REE-fund), động từ nhấn âm 2 (ri-FUND).'),
    ToeicWord('complaint', '/kəmˈpleɪnt/', 'n', 'lời phàn nàn, khiếu nại',
        'We received a complaint about the noise.', 'Chúng tôi nhận được khiếu nại về tiếng ồn.'),
    ToeicWord('campaign', '/kæmˈpeɪn/', 'n', 'chiến dịch',
        'The ad campaign starts next month.', 'Chiến dịch quảng cáo bắt đầu vào tháng sau.', tip: '"g" câm: kam-PAYN.'),
    ToeicWord('market research', '/ˈmɑːr.kɪt rɪˌsɝːtʃ/', 'n', 'nghiên cứu thị trường',
        'Market research shows that customers want lower prices.', 'Nghiên cứu thị trường cho thấy khách muốn giá thấp hơn.'),
    ToeicWord('loyal customer', '/ˈlɔɪ.əl ˈkʌs.tə.mɚ/', 'n', 'khách hàng thân thiết',
        'Loyal customers receive special offers.', 'Khách hàng thân thiết nhận được ưu đãi đặc biệt.'),
    ToeicWord('promote', '/prəˈmoʊt/', 'v', 'quảng bá; thăng chức',
        'We will promote the new product online.', 'Chúng tôi sẽ quảng bá sản phẩm mới trên mạng.'),
    // Công nghệ / IT
    ToeicWord('software', '/ˈsɑːft.wer/', 'n', 'phần mềm',
        'Please install the new software today.', 'Vui lòng cài phần mềm mới trong hôm nay.'),
    ToeicWord('upgrade', '/ˈʌp.ɡreɪd/', 'n', 'sự nâng cấp',
        'The system upgrade will take two hours.', 'Việc nâng cấp hệ thống sẽ mất 2 giờ.'),
    ToeicWord('password', '/ˈpæs.wɝːd/', 'n', 'mật khẩu',
        'Change your password every three months.', 'Hãy đổi mật khẩu 3 tháng một lần.'),
    ToeicWord('malfunction', '/ˌmælˈfʌŋk.ʃən/', 'n', 'sự trục trặc',
        'The delay was caused by an equipment malfunction.', 'Sự chậm trễ là do thiết bị bị trục trặc.'),
    ToeicWord('technician', '/tekˈnɪʃ.ən/', 'n', 'kỹ thuật viên',
        'A technician will fix the printer this afternoon.', 'Kỹ thuật viên sẽ sửa máy in chiều nay.'),
    ToeicWord('database', '/ˈdeɪ.tə.beɪs/', 'n', 'cơ sở dữ liệu',
        'Customer details are stored in our database.', 'Thông tin khách hàng được lưu trong cơ sở dữ liệu.'),
    ToeicWord('device', '/dɪˈvaɪs/', 'n', 'thiết bị',
        'Please turn off all electronic devices.', 'Vui lòng tắt mọi thiết bị điện tử.', tip: 'Danh từ "device" đọc /s/, khác động từ "devise" (nghĩ ra) đọc /z/.'),
    ToeicWord('backup', '/ˈbæk.ʌp/', 'n', 'bản sao lưu',
        'Always keep a backup of important files.', 'Luôn giữ bản sao lưu các tệp quan trọng.'),
    ToeicWord('install', '/ɪnˈstɑːl/', 'v', 'cài đặt, lắp đặt',
        'The IT team will install new computers on Monday.', 'Đội IT sẽ lắp máy tính mới vào thứ Hai.'),
    ToeicWord('log in', '/ˌlɑːɡ ˈɪn/', 'phr', 'đăng nhập',
        'Log in with your employee ID.', 'Đăng nhập bằng mã nhân viên của bạn.'),
    ToeicWord('troubleshoot', '/ˈtrʌb.əl.ʃuːt/', 'v', 'khắc phục sự cố',
        'Our help desk can troubleshoot most problems.', 'Bộ phận hỗ trợ có thể khắc phục hầu hết sự cố.'),
    ToeicWord('compatible', '/kəmˈpæt.ə.bəl/', 'adj', 'tương thích',
        'This app is compatible with all smartphones.', 'Ứng dụng này tương thích với mọi điện thoại thông minh.'),
    // Cơ sở vật chất / xây dựng
    ToeicWord('renovation', '/ˌren.əˈveɪ.ʃən/', 'n', 'việc cải tạo',
        'The lobby is closed for renovation.', 'Sảnh đóng cửa để cải tạo.'),
    ToeicWord('maintenance', '/ˈmeɪn.tən.əns/', 'n', 'việc bảo trì',
        'The elevator is under maintenance.', 'Thang máy đang được bảo trì.', tip: 'Nhấn âm đầu: MAYN-tən-əns (không đọc "main-TAIN-ance").'),
    ToeicWord('facility', '/fəˈsɪl.ə.ti/', 'n', 'cơ sở; tiện nghi',
        'The new facility will open in May.', 'Cơ sở mới sẽ mở cửa vào tháng Năm.'),
    ToeicWord('construction', '/kənˈstrʌk.ʃən/', 'n', 'việc xây dựng',
        'Construction of the bridge began last year.', 'Việc xây cầu bắt đầu từ năm ngoái.'),
    ToeicWord('inspection', '/ɪnˈspek.ʃən/', 'n', 'cuộc kiểm tra',
        'The building passed the safety inspection.', 'Toà nhà đã qua đợt kiểm tra an toàn.'),
    ToeicWord('contractor', '/ˈkɑːn.træk.tɚ/', 'n', 'nhà thầu',
        'We hired a contractor to repair the roof.', 'Chúng tôi thuê nhà thầu sửa mái nhà.'),
    ToeicWord('elevator', '/ˈel.ə.veɪ.tɚ/', 'n', 'thang máy',
        'Take the elevator to the fifth floor.', 'Đi thang máy lên tầng 5.'),
    ToeicWord('blueprint', '/ˈbluː.prɪnt/', 'n', 'bản thiết kế',
        'The architect showed us the blueprint.', 'Kiến trúc sư cho chúng tôi xem bản thiết kế.'),
    ToeicWord('premises', '/ˈprem.ɪ.sɪz/', 'n', 'khuôn viên, cơ sở',
        'Smoking is not allowed on the premises.', 'Không được hút thuốc trong khuôn viên.'),
    // Hợp đồng / pháp lý
    ToeicWord('contract', '/ˈkɑːn.trækt/', 'n', 'hợp đồng',
        'Please read the contract before signing.', 'Vui lòng đọc hợp đồng trước khi ký.', tip: 'Danh từ nhấn âm 1 (KON-trakt), động từ nhấn âm 2 (kən-TRAKT).'),
    ToeicWord('agreement', '/əˈɡriː.mənt/', 'n', 'thoả thuận',
        'The two companies reached an agreement.', 'Hai công ty đã đạt được thoả thuận.'),
    ToeicWord('signature', '/ˈsɪɡ.nə.tʃɚ/', 'n', 'chữ ký',
        'We need your signature on page three.', 'Chúng tôi cần chữ ký của bạn ở trang 3.'),
    ToeicWord('confidential', '/ˌkɑːn.fəˈden.ʃəl/', 'adj', 'bảo mật',
        'This information is strictly confidential.', 'Thông tin này tuyệt đối bảo mật.'),
    ToeicWord('regulation', '/ˌreɡ.jəˈleɪ.ʃən/', 'n', 'quy định',
        'All staff must follow safety regulations.', 'Mọi nhân viên phải tuân thủ quy định an toàn.'),
    ToeicWord('policy', '/ˈpɑː.lə.si/', 'n', 'chính sách',
        'Our return policy allows exchanges within 30 days.', 'Chính sách đổi trả cho phép đổi hàng trong 30 ngày.'),
    ToeicWord('permit', '/ˈpɝː.mɪt/', 'n', 'giấy phép',
        'You need a permit to park here.', 'Bạn cần giấy phép để đỗ xe ở đây.', tip: 'Danh từ nhấn âm 1 (PER-mit), động từ nhấn âm 2 (pər-MIT).'),
    ToeicWord('terms and conditions', '/ˌtɝːmz ənd kənˈdɪʃ.ənz/', 'n', 'điều khoản và điều kiện',
        'Please read the terms and conditions carefully.', 'Vui lòng đọc kỹ điều khoản và điều kiện.'),
    ToeicWord('clause', '/klɑːz/', 'n', 'điều khoản',
        'The contract includes a clause about late payments.', 'Hợp đồng có một điều khoản về việc chậm thanh toán.'),
    ToeicWord('legal', '/ˈliː.ɡəl/', 'adj', 'thuộc về pháp lý',
        'Please contact our legal department.', 'Vui lòng liên hệ phòng pháp chế của chúng tôi.'),
    // Ngân hàng / bảo hiểm
    ToeicWord('account', '/əˈkaʊnt/', 'n', 'tài khoản',
        'I\'d like to open a savings account.', 'Tôi muốn mở một tài khoản tiết kiệm.'),
    ToeicWord('deposit', '/dɪˈpɑː.zɪt/', 'n', 'tiền gửi; tiền đặt cọc',
        'A deposit of \$100 is required.', 'Cần đặt cọc 100 đô.'),
    ToeicWord('withdrawal', '/wɪðˈdrɑː.əl/', 'n', 'việc rút tiền',
        'You can make a withdrawal at any ATM.', 'Bạn có thể rút tiền ở bất kỳ ATM nào.'),
    ToeicWord('interest rate', '/ˈɪn.trəst ˌreɪt/', 'n', 'lãi suất',
        'The bank lowered its interest rate.', 'Ngân hàng đã hạ lãi suất.', tip: '"interest" thường đọc 3 âm: IN-trəst (không đọc IN-tə-rest).'),
    ToeicWord('loan', '/loʊn/', 'n', 'khoản vay',
        'She took out a loan to start her business.', 'Cô ấy vay tiền để khởi nghiệp.'),
    ToeicWord('mortgage', '/ˈmɔːr.ɡɪdʒ/', 'n', 'khoản vay mua nhà (thế chấp)',
        'They pay their mortgage every month.', 'Họ trả khoản vay mua nhà hằng tháng.', tip: '"t" câm: MOR-gij.'),
    ToeicWord('premium', '/ˈpriː.mi.əm/', 'n', 'phí bảo hiểm',
        'The insurance premium is paid yearly.', 'Phí bảo hiểm được đóng hằng năm.'),
    ToeicWord('claim', '/kleɪm/', 'n', 'yêu cầu bồi thường',
        'You can file a claim online.', 'Bạn có thể gửi yêu cầu bồi thường trực tuyến.'),
    ToeicWord('transaction', '/trænˈzæk.ʃən/', 'n', 'giao dịch',
        'Each transaction costs one dollar.', 'Mỗi giao dịch mất 1 đô.'),
    ToeicWord('currency', '/ˈkɝː.ən.si/', 'n', 'tiền tệ',
        'You can exchange currency at the airport.', 'Bạn có thể đổi ngoại tệ ở sân bay.'),
    ToeicWord('exchange rate', '/ɪksˈtʃeɪndʒ ˌreɪt/', 'n', 'tỷ giá',
        'Today\'s exchange rate is good for travelers.', 'Tỷ giá hôm nay có lợi cho khách du lịch.'),
    ToeicWord('coverage', '/ˈkʌv.ɚ.ɪdʒ/', 'n', 'phạm vi bảo hiểm',
        'Does your plan include dental coverage?', 'Gói của bạn có bảo hiểm nha khoa không?'),
    // Y tế / sức khoẻ
    ToeicWord('appointment', '/əˈpɔɪnt.mənt/', 'n', 'cuộc hẹn',
        'I have a dentist appointment at 3 P.M.', 'Tôi có hẹn nha sĩ lúc 3 giờ chiều.'),
    ToeicWord('prescription', '/prɪˈskrɪp.ʃən/', 'n', 'đơn thuốc',
        'You need a prescription for this medicine.', 'Bạn cần đơn thuốc để mua loại thuốc này.'),
    ToeicWord('symptom', '/ˈsɪmp.təm/', 'n', 'triệu chứng',
        'Fever is a common symptom of the flu.', 'Sốt là triệu chứng thường gặp của cúm.'),
    ToeicWord('checkup', '/ˈtʃek.ʌp/', 'n', 'lần khám sức khoẻ định kỳ',
        'Employees get a free annual checkup.', 'Nhân viên được khám sức khoẻ miễn phí hằng năm.'),
    ToeicWord('pharmacy', '/ˈfɑːr.mə.si/', 'n', 'nhà thuốc',
        'The pharmacy is open until 10 P.M.', 'Nhà thuốc mở cửa tới 10 giờ tối.'),
    ToeicWord('insurance', '/ɪnˈʃʊr.əns/', 'n', 'bảo hiểm',
        'Does your insurance cover this treatment?', 'Bảo hiểm của bạn có chi trả cho điều trị này không?'),
    ToeicWord('diagnosis', '/ˌdaɪ.əɡˈnoʊ.sɪs/', 'n', 'sự chẩn đoán',
        'The doctor explained the diagnosis clearly.', 'Bác sĩ giải thích chẩn đoán rất rõ ràng.'),
    ToeicWord('treatment', '/ˈtriːt.mənt/', 'n', 'sự điều trị',
        'The treatment takes about two weeks.', 'Việc điều trị mất khoảng 2 tuần.'),
    ToeicWord('clinic', '/ˈklɪn.ɪk/', 'n', 'phòng khám',
        'The clinic is closed on Sundays.', 'Phòng khám đóng cửa vào Chủ nhật.'),
    // Giáo dục / đào tạo
    ToeicWord('curriculum', '/kəˈrɪk.jə.ləm/', 'n', 'chương trình học',
        'The school updated its curriculum.', 'Trường đã cập nhật chương trình học.'),
    ToeicWord('certificate', '/sɚˈtɪf.ə.kət/', 'n', 'chứng chỉ',
        'You will receive a certificate after the course.', 'Bạn sẽ nhận chứng chỉ sau khoá học.', tip: 'Nhấn âm 2 (sər-TIF-ə-kət), đuôi đọc /kət/.'),
    ToeicWord('enrollment', '/ɪnˈroʊl.mənt/', 'n', 'việc ghi danh',
        'Enrollment for the course closes on May 1.', 'Việc ghi danh khoá học kết thúc ngày 1 tháng 5.'),
    ToeicWord('scholarship', '/ˈskɑː.lɚ.ʃɪp/', 'n', 'học bổng',
        'She won a scholarship to study abroad.', 'Cô ấy giành được học bổng du học.'),
    ToeicWord('lecture', '/ˈlek.tʃɚ/', 'n', 'bài giảng',
        'The lecture will start at 2 P.M.', 'Bài giảng sẽ bắt đầu lúc 2 giờ chiều.'),
    ToeicWord('tuition', '/tuːˈɪʃ.ən/', 'n', 'học phí',
        'Tuition must be paid before classes begin.', 'Học phí phải được đóng trước khi vào học.'),
    ToeicWord('graduate', '/ˈɡrædʒ.u.ət/', 'n', 'người tốt nghiệp',
        'We hire many recent graduates.', 'Chúng tôi tuyển nhiều người mới tốt nghiệp.', tip: 'Danh từ đuôi /ət/; động từ "graduate" đuôi /eɪt/ (GRAJ-oo-ayt).'),
    ToeicWord('instructor', '/ɪnˈstrʌk.tɚ/', 'n', 'người hướng dẫn',
        'The instructor will explain the rules.', 'Người hướng dẫn sẽ giải thích luật.'),
    // Bất động sản / nhà ở
    ToeicWord('lease', '/liːs/', 'n', 'hợp đồng thuê',
        'The lease expires in December.', 'Hợp đồng thuê hết hạn vào tháng 12.'),
    ToeicWord('tenant', '/ˈten.ənt/', 'n', 'người thuê nhà',
        'Tenants must pay rent on the first day of the month.', 'Người thuê phải trả tiền nhà vào ngày đầu tháng.'),
    ToeicWord('landlord', '/ˈlænd.lɔːrd/', 'n', 'chủ nhà cho thuê',
        'Call the landlord if the heater breaks.', 'Gọi chủ nhà nếu máy sưởi bị hỏng.'),
    ToeicWord('property', '/ˈprɑː.pɚ.ti/', 'n', 'bất động sản; tài sản',
        'The property is close to the train station.', 'Bất động sản này gần ga tàu.'),
    ToeicWord('utility bill', '/juːˈtɪl.ə.ti ˌbɪl/', 'n', 'hoá đơn điện nước',
        'The rent does not include utility bills.', 'Tiền thuê chưa gồm hoá đơn điện nước.'),
    ToeicWord('deposit slip', '/dɪˈpɑː.zɪt ˌslɪp/', 'n', 'phiếu nộp tiền',
        'Fill out a deposit slip at the counter.', 'Điền phiếu nộp tiền tại quầy.'),
    ToeicWord('real estate agent', '/ˈriːl ɪˌsteɪt ˌeɪ.dʒənt/', 'n', 'nhân viên môi giới nhà đất',
        'A real estate agent showed us three apartments.', 'Nhân viên môi giới dẫn chúng tôi xem 3 căn hộ.'),
    ToeicWord('furnished', '/ˈfɝː.nɪʃt/', 'adj', 'có sẵn nội thất',
        'The apartment is fully furnished.', 'Căn hộ có đầy đủ nội thất.'),
    // Giao thông / ô tô
    ToeicWord('commute', '/kəˈmjuːt/', 'n', 'quãng đường đi làm hằng ngày',
        'My commute takes about 40 minutes.', 'Tôi đi làm mất khoảng 40 phút.'),
    ToeicWord('traffic jam', '/ˈtræf.ɪk ˌdʒæm/', 'n', 'kẹt xe',
        'I was late because of a traffic jam.', 'Tôi đến muộn vì kẹt xe.'),
    ToeicWord('fare', '/fer/', 'n', 'giá vé (xe, tàu)',
        'The bus fare is two dollars.', 'Giá vé xe buýt là 2 đô.', tip: 'Đọc giống hệt "fair" (công bằng; hội chợ).'),
    ToeicWord('mechanic', '/məˈkæn.ɪk/', 'n', 'thợ máy',
        'The mechanic fixed the brakes.', 'Thợ máy đã sửa phanh.'),
    ToeicWord('vehicle', '/ˈviː.ə.kəl/', 'n', 'phương tiện, xe',
        'Please do not leave your vehicle here.', 'Vui lòng không để xe ở đây.', tip: '"h" câm: VEE-ə-kəl.'),
    ToeicWord('license plate', '/ˈlaɪ.səns ˌpleɪt/', 'n', 'biển số xe',
        'Write down the license plate number.', 'Hãy ghi lại biển số xe.'),
    ToeicWord('detour', '/ˈdiː.tʊr/', 'n', 'đường vòng',
        'Take a detour because the road is closed.', 'Hãy đi đường vòng vì đường bị chặn.'),
    ToeicWord('pedestrian', '/pəˈdes.tri.ən/', 'n', 'người đi bộ',
        'This street is for pedestrians only.', 'Con phố này chỉ dành cho người đi bộ.'),
    // Sự kiện / giải trí
    ToeicWord('venue', '/ˈven.juː/', 'n', 'địa điểm tổ chức',
        'The venue can hold 500 guests.', 'Địa điểm có thể chứa 500 khách.'),
    ToeicWord('audience', '/ˈɑː.di.əns/', 'n', 'khán giả',
        'The audience applauded loudly.', 'Khán giả vỗ tay rầm rộ.'),
    ToeicWord('performance', '/pɚˈfɔːr.məns/', 'n', 'buổi biểu diễn; hiệu suất',
        'Tonight\'s performance starts at 8.', 'Buổi diễn tối nay bắt đầu lúc 8 giờ.'),
    ToeicWord('ticket', '/ˈtɪk.ɪt/', 'n', 'vé',
        'Tickets are available online.', 'Vé có bán trên mạng.'),
    ToeicWord('exhibit', '/ɪɡˈzɪb.ɪt/', 'n', 'cuộc triển lãm; vật trưng bày',
        'The museum has a new exhibit on space.', 'Bảo tàng có triển lãm mới về vũ trụ.', tip: '"h" câm: ig-ZIB-it.'),
    ToeicWord('sponsor', '/ˈspɑːn.sɚ/', 'n', 'nhà tài trợ',
        'The event is supported by local sponsors.', 'Sự kiện được các nhà tài trợ địa phương hỗ trợ.'),
    ToeicWord('banquet', '/ˈbæŋ.kwɪt/', 'n', 'bữa tiệc lớn',
        'The awards banquet will be held at the hotel.', 'Tiệc trao giải sẽ tổ chức ở khách sạn.'),
    ToeicWord('admission', '/ədˈmɪʃ.ən/', 'n', 'phí vào cửa; sự cho vào',
        'Admission is free for children.', 'Trẻ em được vào cửa miễn phí.'),
    // Nhà hàng / ăn uống
    ToeicWord('appetizer', '/ˈæp.ə.taɪ.zɚ/', 'n', 'món khai vị',
        'We ordered soup as an appetizer.', 'Chúng tôi gọi súp làm món khai vị.'),
    ToeicWord('beverage', '/ˈbev.ɚ.ɪdʒ/', 'n', 'đồ uống',
        'Beverages are included in the price.', 'Giá đã bao gồm đồ uống.'),
    ToeicWord('catering', '/ˈkeɪ.tɚ.ɪŋ/', 'n', 'dịch vụ cung cấp tiệc',
        'A catering company will provide lunch.', 'Một công ty dịch vụ tiệc sẽ lo bữa trưa.'),
    ToeicWord('cuisine', '/kwɪˈziːn/', 'n', 'ẩm thực',
        'The restaurant serves Italian cuisine.', 'Nhà hàng phục vụ ẩm thực Ý.', tip: 'Đọc kwi-ZEEN.'),
    ToeicWord('bill', '/bɪl/', 'n', 'hoá đơn',
        'Could we have the bill, please?', 'Cho chúng tôi xin hoá đơn nhé?'),
    ToeicWord('dietary restriction', '/ˈdaɪ.ə.ter.i rɪˌstrɪk.ʃən/', 'n', 'yêu cầu ăn kiêng',
        'Please tell us about any dietary restrictions.', 'Vui lòng cho biết nếu bạn có yêu cầu ăn kiêng.'),
    // Miêu tả tranh (Part 1)
    ToeicWord('lean against', '/ˈliːn əˌɡenst/', 'phr', 'dựa vào',
        'A ladder is leaning against the wall.', 'Một cái thang đang dựa vào tường.'),
    ToeicWord('stack', '/stæk/', 'v', 'xếp chồng',
        'Boxes have been stacked on the floor.', 'Các thùng đã được xếp chồng trên sàn.'),
    ToeicWord('pile', '/paɪl/', 'n', 'đống',
        'There is a pile of papers on the desk.', 'Có một đống giấy trên bàn.'),
    ToeicWord('arrange', '/əˈreɪndʒ/', 'v', 'sắp xếp',
        'Chairs have been arranged in a circle.', 'Ghế đã được xếp thành vòng tròn.'),
    ToeicWord('face', '/feɪs/', 'v', 'quay mặt về phía',
        'The seats are facing the stage.', 'Các ghế đang quay về phía sân khấu.'),
    ToeicWord('browse', '/braʊz/', 'v', 'xem lướt (hàng hoá, sách)',
        'A woman is browsing in a bookstore.', 'Một phụ nữ đang xem lướt trong hiệu sách.'),
    ToeicWord('examine', '/ɪɡˈzæm.ɪn/', 'v', 'xem xét kỹ',
        'A man is examining a document.', 'Một người đàn ông đang xem kỹ tài liệu.'),
    ToeicWord('unload', '/ʌnˈloʊd/', 'v', 'dỡ hàng',
        'Workers are unloading a truck.', 'Công nhân đang dỡ hàng khỏi xe tải.'),
    ToeicWord('sweep', '/swiːp/', 'v', 'quét',
        'A man is sweeping the floor.', 'Một người đàn ông đang quét sàn.'),
    ToeicWord('pour', '/pɔːr/', 'v', 'rót',
        'She is pouring coffee into a cup.', 'Cô ấy đang rót cà phê vào cốc.', tip: 'Đọc giống "pore" /pɔːr/, không đọc "pao".'),
    ToeicWord('hang', '/hæŋ/', 'v', 'treo',
        'Pictures are hanging on the wall.', 'Tranh đang được treo trên tường.'),
    ToeicWord('be lined up', '/bi ˌlaɪnd ˈʌp/', 'phr', 'được xếp thành hàng',
        'Cars are lined up at the gate.', 'Xe đang xếp hàng ở cổng.'),
    ToeicWord('be on display', '/bi ɑːn dɪˈspleɪ/', 'phr', 'được trưng bày',
        'Shoes are on display in the window.', 'Giày đang được trưng bày trong tủ kính.'),
    ToeicWord('kneel', '/niːl/', 'v', 'quỳ',
        'A woman is kneeling in the garden.', 'Một phụ nữ đang quỳ trong vườn.', tip: '"k" câm: NEEL.'),
    ToeicWord('reach for', '/ˈriːtʃ fɔːr/', 'phr', 'với lấy',
        'He is reaching for a book on the shelf.', 'Anh ấy đang với lấy cuốn sách trên kệ.'),
    ToeicWord('wipe', '/waɪp/', 'v', 'lau',
        'She is wiping the table.', 'Cô ấy đang lau bàn.'),
    // Môi trường làm việc chung
    ToeicWord('efficient', '/ɪˈfɪʃ.ənt/', 'adj', 'hiệu quả',
        'The new system is more efficient.', 'Hệ thống mới hiệu quả hơn.'),
    ToeicWord('punctual', '/ˈpʌŋk.tʃu.əl/', 'adj', 'đúng giờ',
        'Please be punctual for the meeting.', 'Vui lòng đến họp đúng giờ.'),
    ToeicWord('flexible', '/ˈflek.sə.bəl/', 'adj', 'linh hoạt',
        'We offer flexible working hours.', 'Chúng tôi có giờ làm việc linh hoạt.'),
    ToeicWord('reliable', '/rɪˈlaɪ.ə.bəl/', 'adj', 'đáng tin cậy',
        'We need a reliable supplier.', 'Chúng ta cần một nhà cung cấp đáng tin cậy.'),
    ToeicWord('thorough', '/ˈθɝː.oʊ/', 'adj', 'kỹ lưỡng',
        'The inspector did a thorough check.', 'Thanh tra đã kiểm tra kỹ lưỡng.', tip: 'Đọc THUR-oh; khác "through" /θruː/ và "though" /ðoʊ/.'),
    ToeicWord('urgent', '/ˈɝː.dʒənt/', 'adj', 'khẩn cấp',
        'I have an urgent message for Ms. Lee.', 'Tôi có tin nhắn khẩn cho bà Lee.'),
    ToeicWord('temporary', '/ˈtem.pə.rer.i/', 'adj', 'tạm thời',
        'This is only a temporary solution.', 'Đây chỉ là giải pháp tạm thời.'),
    ToeicWord('permanent', '/ˈpɝː.mə.nənt/', 'adj', 'lâu dài, chính thức',
        'She was offered a permanent position.', 'Cô ấy được mời vào vị trí chính thức.'),
    ToeicWord('accurate', '/ˈæk.jɚ.ət/', 'adj', 'chính xác',
        'Please make sure the figures are accurate.', 'Hãy chắc chắn các số liệu là chính xác.'),
    ToeicWord('outdated', '/ˌaʊtˈdeɪ.tɪd/', 'adj', 'lỗi thời',
        'Our computers are outdated.', 'Máy tính của chúng ta đã lỗi thời.'),
    // Động từ công sở hay gặp ở Part 5/7
    ToeicWord('submit', '/səbˈmɪt/', 'v', 'nộp',
        'Submit your application by March 1.', 'Hãy nộp đơn trước ngày 1 tháng 3.'),
    ToeicWord('approve', '/əˈpruːv/', 'v', 'phê duyệt',
        'The manager approved my vacation request.', 'Quản lý đã duyệt đơn nghỉ phép của tôi.'),
    ToeicWord('implement', '/ˈɪm.plə.ment/', 'v', 'triển khai',
        'We will implement the new policy next month.', 'Chúng tôi sẽ triển khai chính sách mới vào tháng sau.'),
    ToeicWord('allocate', '/ˈæl.ə.keɪt/', 'v', 'phân bổ',
        'The company allocated \$5,000 for training.', 'Công ty phân bổ 5.000 đô cho việc đào tạo.'),
    ToeicWord('comply with', '/kəmˈplaɪ wɪð/', 'v', 'tuân thủ',
        'All products must comply with safety standards.', 'Mọi sản phẩm phải tuân thủ tiêu chuẩn an toàn.'),
    ToeicWord('verify', '/ˈver.ə.faɪ/', 'v', 'xác minh',
        'Please verify your email address.', 'Vui lòng xác minh địa chỉ email của bạn.'),
    ToeicWord('estimate', '/ˈes.tə.meɪt/', 'v', 'ước tính',
        'We estimate that the project will take six months.', 'Chúng tôi ước tính dự án mất 6 tháng.', tip: 'Động từ đuôi /meɪt/, danh từ "an estimate" đuôi /mət/.'),
    ToeicWord('assign', '/əˈsaɪn/', 'v', 'giao (việc)',
        'The manager assigned the task to Tom.', 'Quản lý đã giao nhiệm vụ cho Tom.', tip: '"g" câm: ə-SINE.'),
    ToeicWord('attend', '/əˈtend/', 'v', 'tham dự',
        'About 200 people attended the seminar.', 'Khoảng 200 người đã dự hội thảo.', tip: 'Không cần "to": attend a meeting (không nói "attend to a meeting").'),
    ToeicWord('recruit', '/rɪˈkruːt/', 'v', 'tuyển dụng',
        'We are recruiting sales staff.', 'Chúng tôi đang tuyển nhân viên bán hàng.'),
    ToeicWord('launch', '/lɑːntʃ/', 'v', 'ra mắt',
        'The company will launch its new phone in May.', 'Công ty sẽ ra mắt điện thoại mới vào tháng Năm.'),
    ToeicWord('expand', '/ɪkˈspænd/', 'v', 'mở rộng',
        'We plan to expand into Asia.', 'Chúng tôi dự định mở rộng sang châu Á.'),
    ToeicWord('exceed', '/ɪkˈsiːd/', 'v', 'vượt quá',
        'Sales exceeded our expectations.', 'Doanh số đã vượt kỳ vọng của chúng tôi.'),
    ToeicWord('acquire', '/əˈkwaɪɚ/', 'v', 'mua lại, giành được',
        'The firm acquired a small software company.', 'Công ty đã mua lại một công ty phần mềm nhỏ.'),
    ToeicWord('merge', '/mɝːdʒ/', 'v', 'sáp nhập',
        'The two banks will merge next year.', 'Hai ngân hàng sẽ sáp nhập vào năm sau.'),
    ToeicWord('outsource', '/ˈaʊt.sɔːrs/', 'v', 'thuê ngoài',
        'We outsource our customer service.', 'Chúng tôi thuê ngoài dịch vụ chăm sóc khách hàng.'),
    ToeicWord('renew', '/rɪˈnuː/', 'v', 'gia hạn',
        'Please renew your membership before it expires.', 'Vui lòng gia hạn thẻ hội viên trước khi hết hạn.'),
    ToeicWord('expire', '/ɪkˈspaɪɚ/', 'v', 'hết hạn',
        'My passport expires next month.', 'Hộ chiếu của tôi hết hạn vào tháng sau.'),
    ToeicWord('refrain from', '/rɪˈfreɪn frəm/', 'v', 'tránh, không làm',
        'Please refrain from using your phone during the show.', 'Vui lòng không sử dụng điện thoại trong buổi diễn.'),
    ToeicWord('accommodate', '/əˈkɑː.mə.deɪt/', 'v', 'đáp ứng; chứa được',
        'The hall can accommodate 300 people.', 'Hội trường chứa được 300 người.'),
    ToeicWord('inquire', '/ɪnˈkwaɪɚ/', 'v', 'hỏi thông tin',
        'I\'m calling to inquire about the job.', 'Tôi gọi để hỏi về công việc.'),
    ToeicWord('confirm', '/kənˈfɝːm/', 'v', 'xác nhận',
        'Please confirm your reservation by email.', 'Vui lòng xác nhận đặt chỗ qua email.'),
    ToeicWord('distribute', '/dɪˈstrɪb.juːt/', 'v', 'phân phát, phân phối',
        'Please distribute these handouts.', 'Vui lòng phát các tài liệu này.'),
    ToeicWord('evaluate', '/ɪˈvæl.ju.eɪt/', 'v', 'đánh giá',
        'We will evaluate all proposals carefully.', 'Chúng tôi sẽ đánh giá kỹ mọi đề xuất.'),
    ToeicWord('anticipate', '/ænˈtɪs.ə.peɪt/', 'v', 'dự đoán, lường trước',
        'We anticipate a busy holiday season.', 'Chúng tôi dự đoán mùa lễ sẽ bận rộn.'),
    ToeicWord('reimburse', '/ˌriː.ɪmˈbɝːs/', 'v', 'hoàn trả (chi phí)',
        'The company will reimburse your travel costs.', 'Công ty sẽ hoàn trả chi phí đi lại cho bạn.'),
    ToeicWord('notify', '/ˈnoʊ.tə.faɪ/', 'v', 'thông báo',
        'Please notify us of any changes.', 'Vui lòng báo cho chúng tôi mọi thay đổi.'),
    ToeicWord('enclose', '/ɪnˈkloʊz/', 'v', 'gửi kèm',
        'I have enclosed a copy of the invoice.', 'Tôi đã gửi kèm bản sao hoá đơn.'),
    ToeicWord('oversee', '/ˌoʊ.vɚˈsiː/', 'v', 'giám sát',
        'Ms. Park will oversee the project.', 'Bà Park sẽ giám sát dự án.'),
    ToeicWord('coordinate', '/koʊˈɔːr.də.neɪt/', 'v', 'điều phối',
        'Kate coordinates all company events.', 'Kate điều phối mọi sự kiện của công ty.'),
    ToeicWord('reserve', '/rɪˈzɝːv/', 'v', 'đặt trước',
        'I reserved a table for eight.', 'Tôi đã đặt bàn cho 8 người.'),
    // Cụm động từ (phrasal verbs)
    ToeicWord('fill out', '/ˌfɪl ˈaʊt/', 'phr', 'điền (mẫu đơn)',
        'Please fill out this form.', 'Vui lòng điền mẫu đơn này.'),
    ToeicWord('set up', '/ˌset ˈʌp/', 'phr', 'thiết lập, sắp đặt',
        'We need to set up the room before the meeting.', 'Chúng ta cần sắp xếp phòng trước cuộc họp.'),
    ToeicWord('look into', '/ˌlʊk ˈɪn.tuː/', 'phr', 'xem xét',
        'We will look into the problem.', 'Chúng tôi sẽ xem xét vấn đề.'),
    ToeicWord('call off', '/ˌkɑːl ˈɑːf/', 'phr', 'huỷ bỏ',
        'The picnic was called off because of rain.', 'Buổi dã ngoại bị huỷ vì mưa.'),
    ToeicWord('put off', '/ˌpʊt ˈɑːf/', 'phr', 'trì hoãn',
        'Don\'t put off your work until tomorrow.', 'Đừng trì hoãn việc tới ngày mai.'),
    ToeicWord('turn down', '/ˌtɝːn ˈdaʊn/', 'phr', 'từ chối; vặn nhỏ',
        'She turned down the job offer.', 'Cô ấy đã từ chối lời mời làm việc.'),
    ToeicWord('carry out', '/ˌker.i ˈaʊt/', 'phr', 'tiến hành',
        'We carried out a customer survey.', 'Chúng tôi đã tiến hành khảo sát khách hàng.'),
    ToeicWord('hand in', '/ˌhænd ˈɪn/', 'phr', 'nộp',
        'Hand in your report by Friday.', 'Nộp báo cáo trước thứ Sáu.'),
    ToeicWord('run out of', '/ˌrʌn ˈaʊt əv/', 'phr', 'hết, cạn',
        'We\'ve run out of paper.', 'Chúng ta hết giấy rồi.'),
    ToeicWord('sign up for', '/ˌsaɪn ˈʌp fɚ/', 'phr', 'đăng ký',
        'I signed up for the yoga class.', 'Tôi đã đăng ký lớp yoga.'),
    ToeicWord('pick up', '/ˌpɪk ˈʌp/', 'phr', 'đón; lấy (hàng)',
        'I\'ll pick you up at the airport.', 'Tôi sẽ đón bạn ở sân bay.'),
    ToeicWord('drop off', '/ˌdrɑːp ˈɑːf/', 'phr', 'giao, để lại',
        'Please drop off the package at the front desk.', 'Vui lòng để gói hàng ở quầy lễ tân.'),
    ToeicWord('go over', '/ˌɡoʊ ˈoʊ.vɚ/', 'phr', 'xem lại kỹ',
        'Let\'s go over the plan once more.', 'Hãy xem lại kế hoạch một lần nữa.'),
    ToeicWord('take over', '/ˌteɪk ˈoʊ.vɚ/', 'phr', 'tiếp quản',
        'Mr. Diaz will take over as manager.', 'Ông Diaz sẽ tiếp quản vị trí quản lý.'),
    ToeicWord('fill in for', '/ˌfɪl ˈɪn fɚ/', 'phr', 'làm thay (ai)',
        'Can you fill in for me tomorrow?', 'Mai bạn làm thay tôi được không?'),
    ToeicWord('catch up on', '/ˌkætʃ ˈʌp ɑːn/', 'phr', 'làm bù, bắt kịp',
        'I need to catch up on my emails.', 'Tôi cần xử lý bù đống email.'),
    ToeicWord('follow up', '/ˌfɑː.loʊ ˈʌp/', 'phr', 'liên hệ lại, theo dõi tiếp',
        'I\'ll follow up with the client tomorrow.', 'Ngày mai tôi sẽ liên hệ lại với khách hàng.'),
    ToeicWord('back up', '/ˌbæk ˈʌp/', 'phr', 'sao lưu; ủng hộ',
        'Remember to back up your files.', 'Nhớ sao lưu các tệp của bạn.'),
    ToeicWord('figure out', '/ˌfɪɡ.jɚ ˈaʊt/', 'phr', 'tìm ra, hiểu ra',
        'We need to figure out why sales dropped.', 'Chúng ta cần tìm ra lý do doanh số giảm.'),
    ToeicWord('set aside', '/ˌset əˈsaɪd/', 'phr', 'dành riêng ra',
        'Please set aside some time for questions.', 'Hãy dành ra ít thời gian cho phần hỏi đáp.'),
    ToeicWord('point out', '/ˌpɔɪnt ˈaʊt/', 'phr', 'chỉ ra',
        'She pointed out a mistake in the report.', 'Cô ấy chỉ ra một lỗi trong báo cáo.'),
    ToeicWord('come up with', '/ˌkʌm ˈʌp wɪð/', 'phr', 'nghĩ ra',
        'Can you come up with a better idea?', 'Bạn có nghĩ ra ý tưởng nào hay hơn không?'),
    // Trạng từ/tính từ hay ra trong bẫy Part 5
    ToeicWord('approximately', '/əˈprɑːk.sə.mət.li/', 'adv', 'xấp xỉ, khoảng',
        'The trip takes approximately two hours.', 'Chuyến đi mất xấp xỉ 2 tiếng.'),
    ToeicWord('promptly', '/ˈprɑːmpt.li/', 'adv', 'ngay lập tức; đúng giờ',
        'The meeting will start promptly at 9.', 'Cuộc họp sẽ bắt đầu đúng 9 giờ.'),
    ToeicWord('previously', '/ˈpriː.vi.əs.li/', 'adv', 'trước đây',
        'She previously worked at a bank.', 'Trước đây cô ấy làm ở ngân hàng.'),
    ToeicWord('currently', '/ˈkɝː.ənt.li/', 'adv', 'hiện tại',
        'The item is currently out of stock.', 'Mặt hàng này hiện đang hết.'),
    ToeicWord('temporarily', '/ˌtem.pəˈrer.əl.i/', 'adv', 'tạm thời',
        'The store is temporarily closed.', 'Cửa hàng tạm thời đóng cửa.'),
    ToeicWord('recently', '/ˈriː.sənt.li/', 'adv', 'gần đây',
        'We recently moved to a new office.', 'Gần đây chúng tôi đã chuyển tới văn phòng mới.'),
    ToeicWord('frequently', '/ˈfriː.kwənt.li/', 'adv', 'thường xuyên',
        'He frequently travels for work.', 'Anh ấy thường xuyên đi công tác.'),
    ToeicWord('immediately', '/ɪˈmiː.di.ət.li/', 'adv', 'ngay lập tức',
        'Please reply immediately.', 'Vui lòng trả lời ngay.'),
    ToeicWord('regularly', '/ˈreɡ.jə.lɚ.li/', 'adv', 'đều đặn',
        'The machines are checked regularly.', 'Máy móc được kiểm tra đều đặn.'),
    ToeicWord('significantly', '/sɪɡˈnɪf.ə.kənt.li/', 'adv', 'đáng kể',
        'Costs have increased significantly.', 'Chi phí đã tăng đáng kể.'),
    ToeicWord('complimentary', '/ˌkɑːm.pləˈmen.tɚ.i/', 'adj', 'miễn phí (tặng kèm)',
        'Guests enjoy a complimentary breakfast.', 'Khách được ăn sáng miễn phí.', tip: 'Đọc giống "complementary" (bổ sung) - chú ý chữ "i" và "e".'),
    ToeicWord('mandatory', '/ˈmæn.də.tɔːr.i/', 'adj', 'bắt buộc',
        'Attendance at the meeting is mandatory.', 'Tham dự cuộc họp là bắt buộc.'),
    ToeicWord('eligible', '/ˈel.ə.dʒə.bəl/', 'adj', 'đủ điều kiện',
        'Full-time staff are eligible for bonuses.', 'Nhân viên toàn thời gian đủ điều kiện nhận thưởng.'),
    ToeicWord('available', '/əˈveɪ.lə.bəl/', 'adj', 'có sẵn; rảnh',
        'Is Mr. Brown available this afternoon?', 'Chiều nay ông Brown có rảnh không?'),
    ToeicWord('affordable', '/əˈfɔːr.də.bəl/', 'adj', 'giá phải chăng',
        'The hotel offers affordable rooms.', 'Khách sạn có phòng giá phải chăng.'),
    ToeicWord('durable', '/ˈdʊr.ə.bəl/', 'adj', 'bền',
        'These bags are light and durable.', 'Những chiếc túi này nhẹ và bền.'),
    ToeicWord('competitive', '/kəmˈpet.ə.tɪv/', 'adj', 'cạnh tranh',
        'We offer a competitive salary.', 'Chúng tôi trả mức lương cạnh tranh.'),
    ToeicWord('substantial', '/səbˈstæn.ʃəl/', 'adj', 'đáng kể, lớn',
        'The company made a substantial investment.', 'Công ty đã đầu tư một khoản lớn.'),
    ToeicWord('tentative', '/ˈten.tə.tɪv/', 'adj', 'dự kiến, chưa chính thức',
        'This is a tentative schedule.', 'Đây là lịch trình dự kiến.'),
    ToeicWord('preliminary', '/prɪˈlɪm.ə.ner.i/', 'adj', 'sơ bộ',
        'The preliminary results look good.', 'Kết quả sơ bộ có vẻ tốt.'),
    ToeicWord('comprehensive', '/ˌkɑːm.prəˈhen.sɪv/', 'adj', 'toàn diện',
        'We offer comprehensive training.', 'Chúng tôi cung cấp chương trình đào tạo toàn diện.'),
    ToeicWord('relevant', '/ˈrel.ə.vənt/', 'adj', 'liên quan',
        'Please include all relevant documents.', 'Vui lòng kèm theo mọi giấy tờ liên quan.'),
    ToeicWord('adjacent', '/əˈdʒeɪ.sənt/', 'adj', 'liền kề',
        'The parking lot is adjacent to the building.', 'Bãi đỗ xe nằm sát toà nhà.', tip: '"d" gần như câm: ə-JAY-sənt.'),
    ToeicWord('spacious', '/ˈspeɪ.ʃəs/', 'adj', 'rộng rãi',
        'The new office is bright and spacious.', 'Văn phòng mới sáng sủa và rộng rãi.'),
    ToeicWord('prestigious', '/presˈtɪdʒ.əs/', 'adj', 'danh giá, uy tín',
        'She graduated from a prestigious university.', 'Cô ấy tốt nghiệp một trường đại học danh giá.'),
    ToeicWord('additional', '/əˈdɪʃ.ən.əl/', 'adj', 'thêm, bổ sung',
        'Additional charges may apply.', 'Có thể tính thêm phí.'),
    ToeicWord('exclusively', '/ɪkˈskluː.sɪv.li/', 'adv', 'chỉ dành riêng',
        'This offer is exclusively for members.', 'Ưu đãi này chỉ dành riêng cho hội viên.'),
    ToeicWord('tremendous', '/trɪˈmen.dəs/', 'adj', 'to lớn',
        'The event was a tremendous success.', 'Sự kiện đã thành công vang dội.'),
    ToeicWord('upcoming', '/ˈʌpˌkʌm.ɪŋ/', 'adj', 'sắp tới',
        'Please register for the upcoming workshop.', 'Vui lòng đăng ký buổi hội thảo sắp tới.'),
    // Danh từ kinh doanh bổ sung
    ToeicWord('quote', '/kwoʊt/', 'n', 'bản báo giá',
        'Can you give me a quote for 100 units?', 'Bạn báo giá cho 100 sản phẩm được không?'),
    ToeicWord('merchandise', '/ˈmɝː.tʃən.daɪs/', 'n', 'hàng hoá',
        'All merchandise is 20 percent off.', 'Mọi hàng hoá đều giảm 20%.'),
    ToeicWord('consumer', '/kənˈsuː.mɚ/', 'n', 'người tiêu dùng',
        'Consumers are spending more online.', 'Người tiêu dùng đang chi tiêu trực tuyến nhiều hơn.'),
    ToeicWord('competitor', '/kəmˈpet.ə.tɚ/', 'n', 'đối thủ cạnh tranh',
        'Our prices are lower than our competitor\'s.', 'Giá của chúng tôi thấp hơn giá của đối thủ.'),
    ToeicWord('shareholder', '/ˈʃerˌhoʊl.dɚ/', 'n', 'cổ đông',
        'The shareholder meeting is in April.', 'Cuộc họp cổ đông diễn ra vào tháng Tư.'),
    ToeicWord('board of directors', '/ˌbɔːrd əv dɪˈrek.tɚz/', 'n', 'hội đồng quản trị',
        'The board of directors approved the plan.', 'Hội đồng quản trị đã duyệt kế hoạch.'),
    ToeicWord('executive', '/ɪɡˈzek.jə.tɪv/', 'n', 'lãnh đạo cấp cao',
        'She is a senior executive at a bank.', 'Cô ấy là lãnh đạo cấp cao ở một ngân hàng.'),
    ToeicWord('personnel', '/ˌpɝː.sənˈel/', 'n', 'nhân sự',
        'Only authorized personnel may enter.', 'Chỉ nhân sự được phép mới được vào.', tip: 'Nhấn âm cuối (per-sə-NEL), khác "personal" (PER-sə-nəl).'),
    ToeicWord('workshop', '/ˈwɝːk.ʃɑːp/', 'n', 'buổi hội thảo thực hành',
        'The workshop teaches basic design skills.', 'Buổi hội thảo dạy kỹ năng thiết kế cơ bản.'),
    ToeicWord('seminar', '/ˈsem.ə.nɑːr/', 'n', 'hội thảo chuyên đề',
        'The seminar on marketing is full.', 'Hội thảo về marketing đã kín chỗ.'),
    ToeicWord('deadline extension', '/ˈded.laɪn ɪkˌsten.ʃən/', 'n', 'sự gia hạn hạn chót',
        'I asked for a deadline extension.', 'Tôi đã xin gia hạn hạn chót.'),
    ToeicWord('questionnaire', '/ˌkwes.tʃəˈner/', 'n', 'bảng câu hỏi',
        'Please complete this short questionnaire.', 'Vui lòng hoàn thành bảng câu hỏi ngắn này.'),
    ToeicWord('survey', '/ˈsɝː.veɪ/', 'n', 'cuộc khảo sát',
        'The survey shows that customers are happy.', 'Khảo sát cho thấy khách hàng hài lòng.', tip: 'Danh từ nhấn âm 1 (SUR-vay), động từ nhấn âm 2 (sər-VAY).'),
    ToeicWord('statement', '/ˈsteɪt.mənt/', 'n', 'bản sao kê; lời tuyên bố',
        'Your bank statement is available online.', 'Bản sao kê ngân hàng của bạn có trên mạng.'),
    ToeicWord('outage', '/ˈaʊ.tɪdʒ/', 'n', 'sự cố mất điện/mạng',
        'A power outage closed the store.', 'Sự cố mất điện khiến cửa hàng phải đóng cửa.'),
    ToeicWord('shortage', '/ˈʃɔːr.tɪdʒ/', 'n', 'sự thiếu hụt',
        'There is a shortage of nurses.', 'Đang thiếu y tá.'),
    ToeicWord('expansion', '/ɪkˈspæn.ʃən/', 'n', 'sự mở rộng',
        'The expansion will create 100 jobs.', 'Việc mở rộng sẽ tạo ra 100 việc làm.'),
    ToeicWord('acquisition', '/ˌæk.wəˈzɪʃ.ən/', 'n', 'thương vụ mua lại',
        'The acquisition was completed in May.', 'Thương vụ mua lại hoàn tất vào tháng Năm.'),
    ToeicWord('commission', '/kəˈmɪʃ.ən/', 'n', 'tiền hoa hồng',
        'Salespeople earn a commission on each sale.', 'Nhân viên bán hàng nhận hoa hồng trên mỗi đơn.'),
    ToeicWord('cost estimate', '/ˈkɑːst ˌes.tə.mət/', 'n', 'bản dự toán chi phí',
        'The contractor sent us a cost estimate.', 'Nhà thầu gửi cho chúng tôi bản dự toán chi phí.'),
    ToeicWord('trade fair', '/ˈtreɪd ˌfer/', 'n', 'hội chợ thương mại',
        'We will have a booth at the trade fair.', 'Chúng tôi sẽ có gian hàng ở hội chợ thương mại.'),
    ToeicWord('keynote speech', '/ˈkiː.noʊt ˌspiːtʃ/', 'n', 'bài phát biểu chính',
        'The CEO will give the keynote speech.', 'CEO sẽ có bài phát biểu chính.'),
    ToeicWord('press release', '/ˈpres rɪˌliːs/', 'n', 'thông cáo báo chí',
        'The company issued a press release this morning.', 'Công ty đã ra thông cáo báo chí sáng nay.'),
    ToeicWord('job opening', '/ˈdʒɑːb ˌoʊ.pən.ɪŋ/', 'n', 'vị trí đang tuyển',
        'There is a job opening in sales.', 'Phòng kinh doanh đang có một vị trí tuyển.'),
    ToeicWord('reference letter', '/ˈref.ɚ.əns ˌlet.ɚ/', 'n', 'thư giới thiệu',
        'My former boss wrote me a reference letter.', 'Sếp cũ đã viết thư giới thiệu cho tôi.'),
    ToeicWord('subsidiary', '/səbˈsɪd.i.er.i/', 'n', 'công ty con',
        'The company opened a subsidiary in Japan.', 'Công ty mở một công ty con ở Nhật.'),
    ToeicWord('franchise', '/ˈfræn.tʃaɪz/', 'n', 'cửa hàng nhượng quyền',
        'He owns a coffee shop franchise.', 'Anh ấy sở hữu một cửa hàng cà phê nhượng quyền.'),
    // Email / thư từ
    ToeicWord('regarding', '/rɪˈɡɑːr.dɪŋ/', 'prep', 'về việc',
        'I\'m writing regarding your recent order.', 'Tôi viết thư về đơn hàng gần đây của bạn.'),
    ToeicWord('feel free to', '/ˌfiːl ˈfriː tuː/', 'phr', 'cứ tự nhiên (làm gì)',
        'Feel free to contact me with any questions.', 'Có câu hỏi gì cứ liên hệ tôi nhé.'),
    ToeicWord('at your convenience', '/æt jɚ kənˈviː.ni.əns/', 'phr', 'lúc nào tiện cho bạn',
        'Please call me at your convenience.', 'Vui lòng gọi cho tôi lúc nào bạn tiện.'),
    ToeicWord('at the latest', '/æt ðə ˈleɪ.tɪst/', 'phr', 'chậm nhất',
        'Send it by Friday at the latest.', 'Gửi chậm nhất là thứ Sáu.'),
    ToeicWord('look forward to', '/ˌlʊk ˈfɔːr.wɚd tuː/', 'phr', 'mong chờ',
        'I look forward to hearing from you.', 'Tôi mong sớm nhận được phản hồi của bạn.', tip: 'Sau "to" dùng V-ing: look forward to hearing (không phải "to hear").'),
    ToeicWord('as soon as possible', '/əz ˌsuːn əz ˈpɑː.sə.bəl/', 'phr', 'càng sớm càng tốt',
        'Please reply as soon as possible.', 'Vui lòng trả lời càng sớm càng tốt.'),
    // Collocation hay gặp
    ToeicWord('meet a deadline', '/ˌmiːt ə ˈded.laɪn/', 'phr', 'kịp hạn chót',
        'We worked late to meet the deadline.', 'Chúng tôi làm muộn để kịp hạn chót.'),
    ToeicWord('place an order', '/ˌpleɪs ən ˈɔːr.dɚ/', 'phr', 'đặt hàng',
        'I\'d like to place an order for 20 chairs.', 'Tôi muốn đặt mua 20 chiếc ghế.'),
    ToeicWord('make a reservation', '/ˌmeɪk ə ˌrez.ɚˈveɪ.ʃən/', 'phr', 'đặt chỗ',
        'Did you make a reservation for dinner?', 'Bạn đã đặt bàn ăn tối chưa?'),
    ToeicWord('hold a meeting', '/ˌhoʊld ə ˈmiː.tɪŋ/', 'phr', 'tổ chức cuộc họp',
        'We will hold a meeting on Monday.', 'Chúng ta sẽ họp vào thứ Hai.'),
    ToeicWord('pay attention to', '/ˌpeɪ əˈten.ʃən tuː/', 'phr', 'chú ý tới',
        'Pay attention to the safety instructions.', 'Hãy chú ý tới hướng dẫn an toàn.'),
    ToeicWord('take into account', '/ˌteɪk ˌɪn.tuː əˈkaʊnt/', 'phr', 'tính đến, cân nhắc',
        'We must take costs into account.', 'Chúng ta phải tính đến chi phí.'),
    ToeicWord('on behalf of', '/ɑːn bɪˈhæf əv/', 'phr', 'thay mặt cho',
        'I\'m writing on behalf of my manager.', 'Tôi viết thư thay mặt quản lý của tôi.', tip: '"l" trong "behalf" câm: bi-HAF.'),
    ToeicWord('in charge of', '/ɪn ˈtʃɑːrdʒ əv/', 'phr', 'phụ trách',
        'Who is in charge of marketing?', 'Ai phụ trách marketing?'),
    ToeicWord('in advance', '/ˌɪn ədˈvæns/', 'phr', 'trước (thời hạn)',
        'Please book your tickets in advance.', 'Vui lòng đặt vé trước.'),
    ToeicWord('out of stock', '/ˌaʊt əv ˈstɑːk/', 'phr', 'hết hàng',
        'This item is out of stock.', 'Mặt hàng này đã hết.'),
    ToeicWord('free of charge', '/ˌfriː əv ˈtʃɑːrdʒ/', 'phr', 'miễn phí',
        'Delivery is free of charge.', 'Giao hàng miễn phí.'),
    ToeicWord('due to', '/ˈduː tuː/', 'phr', 'do, bởi vì',
        'The flight was delayed due to bad weather.', 'Chuyến bay bị hoãn do thời tiết xấu.'),
    ToeicWord('be responsible for', '/bi rɪˈspɑːn.sə.bəl fɚ/', 'phr', 'chịu trách nhiệm',
        'She is responsible for training new staff.', 'Cô ấy chịu trách nhiệm đào tạo nhân viên mới.'),
    ToeicWord('be subject to', '/bi ˈsʌb.dʒekt tuː/', 'phr', 'có thể bị (thay đổi...)',
        'Prices are subject to change.', 'Giá có thể thay đổi.'),
    ToeicWord('in accordance with', '/ɪn əˈkɔːr.dəns wɪð/', 'phr', 'theo đúng',
        'The work was done in accordance with the rules.', 'Công việc được làm theo đúng quy định.'),
    // Tính từ & trạng từ nâng cao (mục tiêu 650)
    ToeicWord('consistent', '/kənˈsɪs.tənt/', 'adj', 'nhất quán, ổn định',
        'Our sales have shown consistent growth.', 'Doanh số của chúng tôi tăng trưởng ổn định.'),
    ToeicWord('considerable', '/kənˈsɪd.ɚ.ə.bəl/', 'adj', 'đáng kể',
        'The project requires a considerable amount of time.', 'Dự án cần một lượng thời gian đáng kể.', tip: 'Hay bị đặt cạnh "considerate" (chu đáo) ở Part 5 - khác nghĩa hoàn toàn.'),
    ToeicWord('considerate', '/kənˈsɪd.ɚ.ət/', 'adj', 'chu đáo, ân cần',
        'It was considerate of you to call.', 'Bạn thật chu đáo khi gọi điện.'),
    ToeicWord('respectively', '/rɪˈspek.tɪv.li/', 'adv', 'lần lượt (theo thứ tự)',
        'Tom and Ann are 25 and 30 years old, respectively.', 'Tom và Ann lần lượt 25 và 30 tuổi.'),
    ToeicWord('reasonably', '/ˈriː.zən.ə.bli/', 'adv', 'hợp lý (giá cả)',
        'The rooms are reasonably priced.', 'Phòng có giá hợp lý.'),
    ToeicWord('exceptionally', '/ɪkˈsep.ʃən.əl.i/', 'adv', 'đặc biệt, cực kỳ',
        'The team performed exceptionally well.', 'Nhóm làm việc đặc biệt tốt.'),
    ToeicWord('properly', '/ˈprɑː.pɚ.li/', 'adv', 'đúng cách',
        'Make sure the machine is properly installed.', 'Hãy chắc chắn máy được lắp đặt đúng cách.'),
    ToeicWord('nearly', '/ˈnɪr.li/', 'adv', 'gần như',
        'The project is nearly finished.', 'Dự án gần như đã xong.'),
    ToeicWord('shortly', '/ˈʃɔːrt.li/', 'adv', 'sớm, ngay sau đây',
        'The train will arrive shortly.', 'Tàu sẽ đến ngay thôi.'),
    ToeicWord('accordingly', '/əˈkɔːr.dɪŋ.li/', 'adv', 'cho phù hợp, theo đó',
        'Plans changed, so we adjusted the budget accordingly.', 'Kế hoạch thay đổi nên chúng tôi điều chỉnh ngân sách cho phù hợp.'),
    ToeicWord('extensive', '/ɪkˈsten.sɪv/', 'adj', 'sâu rộng',
        'She has extensive experience in sales.', 'Cô ấy có kinh nghiệm sâu rộng về bán hàng.'),
    ToeicWord('feasible', '/ˈfiː.zə.bəl/', 'adj', 'khả thi',
        'Is the plan financially feasible?', 'Kế hoạch có khả thi về tài chính không?'),
    ToeicWord('beneficial', '/ˌben.əˈfɪʃ.əl/', 'adj', 'có lợi',
        'Regular exercise is beneficial to health.', 'Tập thể dục đều đặn có lợi cho sức khoẻ.'),
    ToeicWord('routine', '/ruːˈtiːn/', 'adj', 'thường lệ',
        'This is just a routine inspection.', 'Đây chỉ là đợt kiểm tra thường lệ.'),
    // Động từ nâng cao
    ToeicWord('accelerate', '/əkˈsel.ə.reɪt/', 'v', 'đẩy nhanh',
        'We need to accelerate production.', 'Chúng ta cần đẩy nhanh sản xuất.'),
    ToeicWord('adhere to', '/ədˈhɪr tuː/', 'v', 'tuân thủ',
        'All staff must adhere to the dress code.', 'Mọi nhân viên phải tuân thủ quy định trang phục.'),
    ToeicWord('address', '/əˈdres/', 'v', 'giải quyết (vấn đề); phát biểu trước',
        'The manager will address the problem tomorrow.', 'Quản lý sẽ giải quyết vấn đề vào ngày mai.', tip: 'Động từ nhấn âm 2 (ə-DRES); danh từ "địa chỉ" giọng Mỹ thường nhấn âm 1 (A-dres).'),
    ToeicWord('compile', '/kəmˈpaɪl/', 'v', 'tổng hợp (tài liệu)',
        'Please compile a list of all suppliers.', 'Vui lòng tổng hợp danh sách tất cả nhà cung cấp.'),
    ToeicWord('conduct', '/kənˈdʌkt/', 'v', 'tiến hành',
        'We will conduct a survey next month.', 'Chúng tôi sẽ tiến hành khảo sát vào tháng sau.', tip: 'Động từ nhấn âm 2 (kən-DUKT), danh từ nhấn âm 1 (KON-dukt).'),
    ToeicWord('delegate', '/ˈdel.ə.ɡeɪt/', 'v', 'giao, uỷ thác (việc)',
        'Good managers delegate tasks to their team.', 'Quản lý giỏi biết giao việc cho nhóm.'),
    ToeicWord('designate', '/ˈdez.ɪɡ.neɪt/', 'v', 'chỉ định',
        'This area is designated for smoking.', 'Khu vực này được chỉ định để hút thuốc.'),
    ToeicWord('enhance', '/ɪnˈhæns/', 'v', 'nâng cao, cải thiện',
        'The training will enhance your skills.', 'Khoá đào tạo sẽ nâng cao kỹ năng của bạn.'),
    ToeicWord('ensure', '/ɪnˈʃʊr/', 'v', 'đảm bảo',
        'Please ensure that all doors are locked.', 'Vui lòng đảm bảo mọi cửa đã khoá.', tip: 'Đọc gần giống "insure" (mua bảo hiểm) - phân biệt bằng nghĩa.'),
    ToeicWord('facilitate', '/fəˈsɪl.ə.teɪt/', 'v', 'tạo điều kiện, hỗ trợ',
        'The new system will facilitate communication.', 'Hệ thống mới sẽ hỗ trợ việc giao tiếp.'),
    ToeicWord('forward', '/ˈfɔːr.wɚd/', 'v', 'chuyển tiếp (email)',
        'I will forward the email to you.', 'Tôi sẽ chuyển tiếp email cho bạn.'),
    ToeicWord('obtain', '/əbˈteɪn/', 'v', 'có được, xin được',
        'You must obtain a permit first.', 'Bạn phải xin được giấy phép trước.'),
    ToeicWord('prioritize', '/praɪˈɔːr.ə.taɪz/', 'v', 'ưu tiên',
        'We need to prioritize customer requests.', 'Chúng ta cần ưu tiên yêu cầu của khách hàng.'),
    ToeicWord('retain', '/rɪˈteɪn/', 'v', 'giữ lại',
        'The company wants to retain its best employees.', 'Công ty muốn giữ chân nhân viên giỏi nhất.'),
    ToeicWord('revise', '/rɪˈvaɪz/', 'v', 'sửa đổi',
        'Please revise the report before Friday.', 'Vui lòng sửa lại báo cáo trước thứ Sáu.'),
    ToeicWord('streamline', '/ˈstriːm.laɪn/', 'v', 'tinh gọn',
        'The new software will streamline the process.', 'Phần mềm mới sẽ tinh gọn quy trình.'),
    ToeicWord('waive', '/weɪv/', 'v', 'miễn (phí, yêu cầu)',
        'The bank will waive the fee for new customers.', 'Ngân hàng sẽ miễn phí cho khách hàng mới.', tip: 'Đọc giống hệt "wave" (vẫy tay).'),
    // Danh từ nâng cao
    ToeicWord('amenity', '/əˈmen.ə.ti/', 'n', 'tiện nghi',
        'The hotel offers many amenities, including a pool.', 'Khách sạn có nhiều tiện nghi, gồm cả hồ bơi.'),
    ToeicWord('attire', '/əˈtaɪɚ/', 'n', 'trang phục',
        'Business attire is required at the event.', 'Sự kiện yêu cầu trang phục công sở.'),
    ToeicWord('capacity', '/kəˈpæs.ə.ti/', 'n', 'sức chứa; năng lực',
        'The hall has a capacity of 500 people.', 'Hội trường có sức chứa 500 người.'),
    ToeicWord('compensation', '/ˌkɑːm.penˈseɪ.ʃən/', 'n', 'bồi thường; thù lao',
        'Employees receive compensation for overtime.', 'Nhân viên được trả thêm khi làm ngoài giờ.'),
    ToeicWord('component', '/kəmˈpoʊ.nənt/', 'n', 'linh kiện, thành phần',
        'We import some components from Japan.', 'Chúng tôi nhập một số linh kiện từ Nhật.'),
    ToeicWord('criteria', '/kraɪˈtɪr.i.ə/', 'n', 'các tiêu chí',
        'The selection criteria are listed below.', 'Các tiêu chí lựa chọn được liệt kê bên dưới.', tip: 'Là số nhiều của "criterion" - đi với động từ số nhiều (criteria ARE).'),
    ToeicWord('directory', '/dəˈrek.tɚ.i/', 'n', 'danh bạ, bảng chỉ dẫn',
        'Check the building directory in the lobby.', 'Hãy xem bảng chỉ dẫn toà nhà ở sảnh.'),
    ToeicWord('dividend', '/ˈdɪv.ə.dend/', 'n', 'cổ tức',
        'Shareholders will receive a dividend this year.', 'Cổ đông sẽ nhận cổ tức năm nay.'),
    ToeicWord('entrepreneur', '/ˌɑːn.trə.prəˈnɝː/', 'n', 'doanh nhân khởi nghiệp',
        'She is a successful young entrepreneur.', 'Cô ấy là một doanh nhân trẻ thành công.', tip: 'Từ gốc Pháp: ahn-trə-prə-NUR (nhấn âm cuối).'),
    ToeicWord('incentive', '/ɪnˈsen.tɪv/', 'n', 'khoản khuyến khích, thưởng',
        'Sales staff receive an incentive for each new client.', 'Nhân viên bán hàng nhận thưởng cho mỗi khách mới.'),
    ToeicWord('initiative', '/ɪˈnɪʃ.ə.tɪv/', 'n', 'sáng kiến; sự chủ động',
        'The company launched a new recycling initiative.', 'Công ty đưa ra sáng kiến tái chế mới.'),
    ToeicWord('liability', '/ˌlaɪ.əˈbɪl.ə.ti/', 'n', 'trách nhiệm pháp lý',
        'The company has no liability for lost items.', 'Công ty không chịu trách nhiệm với đồ thất lạc.'),
    ToeicWord('margin', '/ˈmɑːr.dʒɪn/', 'n', 'biên (lợi nhuận)',
        'Our profit margin increased this year.', 'Biên lợi nhuận của chúng tôi tăng năm nay.'),
    ToeicWord('patron', '/ˈpeɪ.trən/', 'n', 'khách quen; bạn đọc',
        'Library patrons can borrow up to ten books.', 'Bạn đọc của thư viện được mượn tối đa 10 cuốn.'),
    ToeicWord('proximity', '/prɑːkˈsɪm.ə.ti/', 'n', 'sự gần kề',
        'The proximity of the hotel to the airport is convenient.', 'Việc khách sạn gần sân bay rất tiện.'),
    ToeicWord('quota', '/ˈkwoʊ.tə/', 'n', 'chỉ tiêu',
        'Each salesperson has a monthly quota.', 'Mỗi nhân viên bán hàng có chỉ tiêu hằng tháng.'),
    ToeicWord('reception', '/rɪˈsep.ʃən/', 'n', 'tiệc chiêu đãi; quầy lễ tân',
        'A reception will follow the ceremony.', 'Sau buổi lễ sẽ có tiệc chiêu đãi.'),
    ToeicWord('refreshments', '/rɪˈfreʃ.mənts/', 'n', 'đồ ăn nhẹ, nước uống',
        'Refreshments will be served during the break.', 'Đồ ăn nhẹ sẽ được phục vụ trong giờ giải lao.'),
    ToeicWord('turnover', '/ˈtɝːnˌoʊ.vɚ/', 'n', 'tỷ lệ nghỉ việc; doanh thu',
        'The company has a low staff turnover.', 'Công ty có tỷ lệ nhân viên nghỉ việc thấp.'),
    // Cụm từ công sở bổ sung
    ToeicWord('on short notice', '/ɑːn ˌʃɔːrt ˈnoʊ.tɪs/', 'phr', 'báo gấp',
        'Thank you for coming on short notice.', 'Cảm ơn bạn đã đến dù được báo gấp.'),
    ToeicWord('up to date', '/ˌʌp tə ˈdeɪt/', 'phr', 'cập nhật mới nhất',
        'Please keep your contact information up to date.', 'Vui lòng cập nhật thông tin liên lạc của bạn.'),
    ToeicWord('in person', '/ɪn ˈpɝː.sən/', 'phr', 'trực tiếp',
        'Applications must be submitted in person.', 'Hồ sơ phải được nộp trực tiếp.'),
    ToeicWord('out of order', '/ˌaʊt əv ˈɔːr.dɚ/', 'phr', 'bị hỏng',
        'The vending machine is out of order.', 'Máy bán hàng tự động bị hỏng.'),
    ToeicWord('at no extra cost', '/æt noʊ ˌek.strə ˈkɑːst/', 'phr', 'không mất thêm phí',
        'We deliver at no extra cost.', 'Chúng tôi giao hàng không tính thêm phí.'),
    ToeicWord('on time', '/ɑːn ˈtaɪm/', 'phr', 'đúng giờ',
        'The train arrived on time.', 'Tàu đến đúng giờ.', tip: 'Khác "in time" (kịp lúc, trước khi quá muộn).'),
    ToeicWord('in time', '/ɪn ˈtaɪm/', 'phr', 'kịp lúc',
        'We arrived just in time for the meeting.', 'Chúng tôi đến vừa kịp cuộc họp.'),
    ToeicWord('as of', '/ˈæz əv/', 'phr', 'kể từ (ngày)',
        'As of Monday, the office will open at 8.', 'Kể từ thứ Hai, văn phòng mở cửa lúc 8 giờ.'),
    ToeicWord('in the meantime', '/ɪn ðə ˈmiːn.taɪm/', 'phr', 'trong lúc đó',
        'In the meantime, please use the other printer.', 'Trong lúc đó, vui lòng dùng máy in khác.'),
    ToeicWord('with regard to', '/wɪð rɪˈɡɑːrd tuː/', 'phr', 'về vấn đề',
        'I am writing with regard to your order.', 'Tôi viết thư về đơn hàng của bạn.'),
  ];
}
